# Generated by Django 3.1.6 on 2021-02-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones', models.IntegerField()),
                ('cooperacion', models.IntegerField()),
                ('supervision', models.IntegerField()),
                ('condicionesfisicas', models.IntegerField()),
                ('satisfaccion', models.IntegerField()),
                ('participacion', models.IntegerField()),
            ],
        ),
    ]
